baseURL = "https://prajwalnayak7.github.io/"
languageCode = "en-us"
title = "Prajwal Nayak"
theme = "paper"

[taxonomies]
    tag = "tags"
[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = -120
[permalinks]
    post = "/:slug/"
    page = "/:slug/"